export const dummyData = [
  {
    sessionId: 1,
    title: 'Casual chat',
    chatId: 0,
    userId: 7,
    role: 'user',
    timestamp: '2024-09-01T12:00:00Z',
    content: 'Hi, tell me what you do?',
  },
  {
    sessionId: 1,
    title: 'Casual chat',
    chatId: 1,
    role: 'assistant',
    timestamp: '2024-09-01T12:00:10Z',
    content: 'Hi! I am your personal assistant. How can I help you?',
  },
  {
    sessionId: 1,
    title: 'Casual chat',
    chatId: 2,
    userId: 7,
    role: 'user',
    timestamp: '2024-09-01T12:00:30Z',
    content: 'Write me some code that does...',
  },
  {
    sessionId: 2,
    title: 'Chat from past',
    chatId: 0,
    userId: 7,
    role: 'user',
    timestamp: '2024-09-02T08:00:00Z',
    content: 'Hey, remember the code you wrote?',
  },
  {
    sessionId: 2,
    title: 'Chat from past',
    chatId: 1,
    role: 'assistant',
    timestamp: '2024-09-02T08:00:20Z',
    content: "I'm sorry, I don't remember the code you are referring to.",
  },
];
