export const POSTGRES_DATA_SOURCE = "POSTGRES_DATA_SOURCE";

export const JOB_REPOSITORY = "JOB_REPOSITORY";
export const RUN_REPOSITORY = "RUN_REPOSITORY";
export const DATASET_REPOSITORY = "DATASET_REPOSITORY";
export const RUN_EVENT_REPOSITORY = "RUN_EVENT_REPOSITORY";
export const RUN_DATASET_REPOSITORY = "RUN_DATASET_REPOSITORY";
